[package]
name = "random_quote_api"
version = "0.1.0"
authors = ["Anh Ngoc <nguyenanhngoc.ftu@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.10"
serde_json = "1.0.39"
serde = "1.0.89"
serde_derive = "1.0.89"
scraper = "0.9.1"
regex = "1"
rand = "*"